name: barwah_app
description: "Barwah Elmazoury Financial and Field Management Application"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Localization & Internationalization (عربي / إنجليزي)
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.3

  # State Management
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5

  # Dependency Injection & Functional Programming
  get_it: ^7.7.0
  dartz: ^0.10.1

  # Network & API Handling
  dio: ^5.4.3+1

  # Local Storage (لحفظ لغة التطبيق وتوكن الدخول)
  shared_preferences: ^2.2.3

  # Icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  generate: true # لتفعيل التوليد التلقائي لملفات الترجمة l10n

  # مجلد الخطوط والأصول (اختياري عند إضافة خط Cairo أو الأيقونات)
  # assets:
  #   - assets/images/
  #   - assets/icons/